// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzy1Abd0p7N9g3Cjpxeky12BMzD7Qcacc',
    appId: '1:481371472917:web:4a38cf7a487fe0cff0ba1c',
    messagingSenderId: '481371472917',
    projectId: 'helpserviceappjawan',
    authDomain: 'helpserviceappjawan.firebaseapp.com',
    storageBucket: 'helpserviceappjawan.appspot.com',
    measurementId: 'G-TJ08S9VJ6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMzeg2Ue0OFKjmKxQ9CqPAtSnBNvN1l34',
    appId: '1:481371472917:android:a2b6b61913cac698f0ba1c',
    messagingSenderId: '481371472917',
    projectId: 'helpserviceappjawan',
    storageBucket: 'helpserviceappjawan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLeql85TyL7A_pqpjnFDjSZgzZScUJyyg',
    appId: '1:481371472917:ios:29636149c9775206f0ba1c',
    messagingSenderId: '481371472917',
    projectId: 'helpserviceappjawan',
    storageBucket: 'helpserviceappjawan.appspot.com',
    iosClientId: '481371472917-5dnm4u03kvd5a4vh9jtadotvkv423knk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLeql85TyL7A_pqpjnFDjSZgzZScUJyyg',
    appId: '1:481371472917:ios:29636149c9775206f0ba1c',
    messagingSenderId: '481371472917',
    projectId: 'helpserviceappjawan',
    storageBucket: 'helpserviceappjawan.appspot.com',
    iosClientId: '481371472917-5dnm4u03kvd5a4vh9jtadotvkv423knk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
